version: '2'
services:
  postgres_test:
    image: postgres:15
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - 5557:5432
  zookeeper_test:
    image: confluentinc/cp-zookeeper:6.0.1
    ports:
      - 32185:32185
    environment:
      ZOOKEEPER_CLIENT_PORT: 32185
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"
      - "localhost:127.0.0.1"
  kafka_test:
    image: confluentinc/cp-kafka:6.0.1
    ports:
      - 29097:29097
    depends_on:
      - zookeeper_test
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_test:32185
      KAFKA_LISTENERS: "INTERNAL://:9093,EXTERNAL://:29097"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka_test:9093,EXTERNAL://localhost:29097"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 5
    extra_hosts:
      - "moby:127.0.0.1"
      - "localhost:127.0.0.1"