name: Publish
on:
  push:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build
        run: |
          ./gradlew jreleaserConfig
          ./gradlew publish -x test
          ./gradlew jreleaserDeploy
        env:
          JRELEASER_GPG_SECRET_KEY: '${{secrets.GPG_SECRET_KEY}}'
          JRELEASER_GPG_PUBLIC_KEY: '${{secrets.GPG_PUBLIC_KEY}}'
          JRELEASER_MAVENCENTRAL_USERNAME: '${{secrets.SONATYPE_USERNAME}}'
          JRELEASER_MAVENCENTRAL_PASSWORD: '${{secrets.SONATYPE_PASSWORD}}'
          JRELEASER_NEXUS2_USERNAME: '${{secrets.SONATYPE_USERNAME}}'
          JRELEASER_NEXUS2_PASSWORD: '${{secrets.SONATYPE_PASSWORD}}'
          JRELEASER_GPG_PASSPHRASE: '${{secrets.PGP_PASSPHRASE}}'