name: Release thoth
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'release version'
        required: true
      nextVersion:
        description: 'next version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: release gradle
        run: |
          git config --local user.email "thoth-github-actions@users.noreply.github.com"
          git config --local user.name "thoth-github-actions"
          ./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ github.event.inputs.releaseVersion }} -Prelease.newVersion=${{ github.event.inputs.nextVersion }}
      - name: Push tag
        run: |
          echo "created=true" >> "$GITHUB_OUTPUT"
          git push origin v${{ github.event.inputs.releaseVersion }}
      - name: Create github release
        run: gh release create "v${{ github.event.inputs.releaseversion }}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}